require("tj.base")
require("tj.keymaps")
require("tj.plugins")
require("tj.colorscheme")
require("tj.telescope")
require("tj.cmp")
require("tj.lsp")
require("tj.lualine")
require("tj.autopairs")
require("tj.treesitter")
require("tj.comment")
require("tj.gitsigns")
-- require("tj.nvim-tree")
require("tj.project")
require("tj.rest")
require("tj.indentline")
